### ISSUE TITLE
请教这个支持本地GPT模型调用吗,是否有代码参考,感谢

### ISSUE THREAD

**Issue by hanetyb** [MandyDai/weChatRobot#30]

**Comment by MartinDai** [comment]
你如果有本地模型的话，可以参考ChatGptService进行实现
我没做过本地GPT模型，后续我可以研究一下
你也可以提供一下你的本地GPT模型信息

**Comment by hanetyb** [comment]
这两个模型，我也可以把我的环境给你 一起玩，如果感兴趣..

![图片](https://github.com/MartinDai/weChatRobot/assets/136415996/f2ce0c47-71cf-4219-bc15-d7dcd65266d8)

**Comment by MartinDai** [comment]
@hanetyb 可以把你的联系方式发我邮箱，这俩模型我有空本地部署一下试试

**Comment by MartinDai** [comment]
已支持OPENAI_SERVER_URL参数以配置符合openai规范的GPT模型调用

**Comment by hanetyb** [comment]
非常感谢，必须加星
